### PR TITLE
Make user interactions a list

### PR DESCRIPTION
**Pull request by kreediam**
Fixes mfilippov/vimeo-dot-net#204

### CODE REVIEW

**Comment by DanPatten** [comment]
If Vimeo reverts their changes then this will break again.

**Comment by gtsoftwareltd** [comment]
While the code change does get Vimeo interactions working again, the project unit tests are broken by the change.
The unit tests need the JSON files updating so "interactions" are in an array '[' .. ']'

src/VimeoDotNet.Tests/TestData/Channel/channels.json
src/VimeoDotNet.Tests/TestData/Album/albums-115220313.json
src/VimeoDotNet.Tests/TestData/Video/video-208799259.json
src/VimeoDotNet.Tests/TestData/Video/video-417178750.json

Note that not all "interactions" change to array as ChannelMetadata and VideoMetadata also have "interactions" properties.

Changing the unit test JSON files and UserMetadata feel like a sticking plaster. A sticking plaster that I also need for an application, so I'm content for a rapid update to fix the immediate issue.

I have not confirmed the raw Vimeo API responses and I wonder if the other "interactions" might change soon too.

**Comment by kreediam** [comment]
Thank you @gtsoftwareltd. This change did work for my specific case, but like you said I'm not sure it's correct in all uses. More testing is needed.

**Comment by gtsoftwareltd** [comment]
Not going to usurp your PR. You can take the JSON updates from https://github.com/gtsoftwareltd/vimeo-dot-net-issue205.git 

They are simple changes but really tedious to make.

**Comment by christophbrunner** [comment]
In the meantime, vimeo has probably reversed the change. Everything is working again for us

**Comment by gtsoftwareltd** [comment]
> In the meantime, vimeo has probably reversed the change. Everything is working again for us

Yesterday I raised a support note with Vimeo who have just replied:

"We would like to inform you that our development team has recently implemented a fix that may resolve this issue. 
Could you kindly verify this on your end and provide us with an update?"

I think they have reverted whatever 'broke' yesterday.

Since vimeo-dot-net is a community client, I had sent Vimeo support an example using the official PyVimeo client

```
import vimeo
import secrets

client = vimeo.VimeoClient(token=f'{secrets.access_token}')

x = client.get('/me/albums')

print(x.content)
```

This morning it produced a (large) JSON response that contained an array for "interactions"

```
                        },
                        "block": {
                            "uri": "/me/block",
                            "options": [
                                "GET"
                            ],
                            "total": 0
                        }
                    },
                    "interactions": []              <----- The new array
                },
                "location_details": {
                    "formatted_address": "",
```

This afternoon, following the response from Vimeo support, the same script runs to produce a JSON response where "interactions" are not present

```
                        },
                        "block": {
                            "uri": "/me/block",
                            "options": [
                                "GET"
                            ],
                            "total": 0
                        }
                    }
                },                          <-- no interactions
                "location_details": {
                    "formatted_address": "",
```

I conclude that they've reverted the change, so this pull request is not now needed.

**Pull request closed without merging**
