### PR TITLE
Adding video search capability

### PR DESCRIPTION
**Pull request by justinspradlin**
Adds the query parameter to video searches. Allows users to perform
paged searches for videos.

### CODE REVIEW

**Comment by justinspradlin** [comment]
@mfilippov thanks for merging this in. Would it be possible for you to push an update to the nuget package? I'm developing a plugin for Umbraco a .NET CMS and would like to use the nuget dependency. Right now I have to build from my local copy to have this search feature. 

Thanks!

**Comment by mfilippov** [comment]
Yes i do it today.

**Comment by justinspradlin** [comment]
@mfilippov, I hate to bug you as I'm sure your time is limited, but do you have some time to push the latest version up to nuget? Thanks in advance!

**Comment by mfilippov** [comment]
@justinspradlin I do it, sorry for delay I create normal build script. In future I try avoid delays.

**Comment by justinspradlin** [comment]
Awesome thanks again!

**Pull request merged**
