### PR TITLE
Add support for uploading, updating, and deleting text tracks.

### PR DESCRIPTION
**Pull request by needham-develop**

### CODE REVIEW

**Comment by needham-develop** [comment]
@mfilippov I realize this is probably at the bottom of your priority list, but if you get a couple of spare cycles please have a look. I could ask all groups here to use my fork but would rather they use the NuGet package. BTW all integration test pass for me, looks like the CI just needs a test account and credentials.

**Comment by mfilippov** [comment]
@needham-develop Thanks for a contibution. I try deploy new NuGet on weekend.

**Comment by needham-develop** [comment]
I also added support for getting the api rate limiting information from Vimeo.

**Comment by mfilippov** [comment]
I try check you commits on this week.

**Comment by mfilippov** [comment]
I fix integration tests on appVeyor. @needham-develop please update your branch for verification.

**Comment by needham-develop** [comment]
@mfilippov ok I think I was able to accomplish it, was kinda twisted, seems like I must be missing a way to easily merge from your repo to my fork.

**Comment by scommisso** [comment]
I would suggest a rebase

**Comment by needham-develop** [comment]
I was unable to find a way to do it in the desktop client or VS2015. Neither would allow me to "rebase" or "merge" between the main repo and my fork. What I did was make a PR from the main repo to my fork then merge that, and then create a PR from that new branch to my master and merge. It worked.

So then if I want to rebase or merge between repos does it have to be the command line?

**Comment by mfilippov** [comment]
I fix some issues in tests and put it in another PR https://github.com/mfilippov/vimeo-dot-net/pull/63

**Pull request closed without merging**
