### PR TITLE
* Add support for "pull"

### PR DESCRIPTION
**Pull request by mohibsheth**

### CODE REVIEW

**Comment by mfilippov** [comment]
@mohibsheth Thank you for contribution. I change some API. Please update your PR for new API. Also please add a test for your case if it possible.

**Comment by mfilippov** [comment]
@mohibsheth Please add link on #50 in your commit message

**Comment by mohibsheth** [comment]
@mfilippov I tried the best I could. Couldn't compile the Test project as I don't have VS2017 yet. Let me know if you face any issue.

**Comment by mfilippov** [comment]
Thanks for the contribution. I try to add tests for this case later.

**Pull request merged**
