### PR TITLE
Allow user to get all the videos by project id

### PR DESCRIPTION
**Pull request by karan12990**
Created GetAllVideosFromFolderAsync method which wil return all the videos uploaded by users into the folder (project) by id.

### CODE REVIEW

**Comment by mfilippov** [comment]
@karan12990 Thank you for the contribution. Why are you change LICENSE and project name in this PR?

**Comment by karan12990** [comment]
@mfilippov 
Sorry by mistake its appear as i change and commit its there in the PR.

**Comment by mfilippov** [comment]
@karan12990 Ok, thank you for the answer. I am waiting for the PR update.

**Comment by karan12990** [comment]
Hello @mfilippov ,


Created new [PR](https://github.com/mfilippov/vimeo-dot-net/pull/164) and closing this.

Thanks.

**Pull request closed without merging**
