### PR TITLE
Fixes to successfully upload a video

### PR DESCRIPTION
**Pull request by MattHartz**
Updated VerifyUpload to get a 308 instead of 200.
Put Video now supplies content range and length for chunked upload.

### CODE REVIEW

**Comment by MattHartz** [comment]
@mfilippov Here is the fixes I was mentioning.  Basically, Verify upload wasn't checking the amount of bytes that were successfully uploaded and therefore succeeded when it really shouldn't have.  I also changed it to then supply the content ranges when supplying chunks.

Let me know if you have any questions

**Comment by mfilippov** [comment]
@MattHartz Thanks for the contribution again!

**Comment by MattHartz** [comment]
@mfilippov Is this already up on Nuget? I see 0.9.0.11 for the last pull request.

**Comment by MattHartz** [comment]
@mfilippov Nevermind, now it showed up :) 👍

**Comment by mfilippov** [comment]
@MattHartz Yes, it is. But maybe need some time for cache update.

**Pull request merged**
