### PR TITLE
Add tus resumable upload functionality from api version 3.4

### PR DESCRIPTION
**Pull request by badams229**
Allows user to specify the tus upload approach when opening an upload ticket

### CODE REVIEW

**Comment by mfilippov** [comment]
@badams229 Thank you for the contribution!

**Comment by rkalasky** [comment]
@mfilippov any thought on when this will be released?

**Comment by mfilippov** [comment]
I try to do it today.

**Comment by mfilippov** [comment]
@rkalasky 2.0.0.19 released with fixes. Sorry for the delay.

**Pull request merged**
