### PR TITLE
Text track support

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Comment by mfilippov** [comment]
@needham-develop Thank you for contribution.

**Comment by needham-develop** [comment]
@mfilippov Happy to contribute. Having the project has saved me a lot of development time.

**Comment by mfilippov** [comment]
@needham-develop This changes released on NuGet. I setup auto-deployment process for fast deployment in the future.

**Comment by needham-develop** [comment]
@mfilippov Thank You

**Pull request merged**
