### PR TITLE
WIP for filtering

### PR DESCRIPTION
**Pull request by RobMalvern**
Adding support for JSON filters  #86 , incomplete - committed for discussion.

There are quite a few ways to do this. I've implemented one way on the GetAlbumVideosAsync function. Please give feedback, when we're both happy,, I'll add it to the rest of the library.

### CODE REVIEW

**Comment by mfilippov** [comment]
Looks good. Could you add tests for this request to check problems when some fields not exist?

**Comment by mfilippov** [comment]
@RobMalvern Is it ready to merge?

**Comment by RobMalvern** [comment]
Yes I think so, unless there are any unit tests or API calls I've missed?

**Comment by mfilippov** [comment]
Thanks for the contribution I check all API later.

**Pull request merged**
